### ISSUE TITLE
Preventing loading from certain directories

### ISSUE THREAD

**Issue by Felix14-v2** [EZForever/ThatOrThis#15]
In some situations it would bee useful to be able to prevent loading mods from certain directories or other rule objects. For example when user want to load a mod that is incompatible with another loaded mod, this is a good precaution.

Is it possible to implement something like this?

**Comment by EZForever** [comment]
tl, dr: Theorically yes, but no without many design change. Some features can be implemented in other ways currently.

> prevent loading mods from certain directories or other rule objects

For GENERATED and NESTED rules (the rules that opens a new settings screen), this can be achieved via the lock button. However it's up to the user whether to use it.

> when user want to load a mod that is incompatible with another loaded mod

Incompatible mod sets are typically separated to different options of a DEFINED rule. If you choose one option, the other options are not chosen and therefore mods are not loaded.

I've been thinking about implementing some kind of logic in the config file well before publishing this mod, something like boolean expressions (mod1 ^ (mod2 && mod3)) or dependency manifests (like "depends" and "breaks" fields in fabric.mods.json). But this would be relatively a mess to implement, so with v0.1.0 I've come up with the DEFINED rules: "directories" fields are ANDs, a rule itself is XOR (w/ NOT capability), and the whole ruleset is OR. This is not to say the current ruleset format is not a mess, but it's the best I can get without creating a larger mess.

Maybe in the future when ThatOrThis becomes like a "package manager" for mods (see #8), a proper way of defining logic between rules can be designed.
