### ISSUE TITLE
[bug] looks for mods/mods/ on server

### ISSUE THREAD

**Issue by supersaiyansubtlety** [EZForever/ThatOrThis#2]
I have a client+server environments and I'm trying to use thatorthis to allow me to load client-only mods only on the client and server-only mods only on the server. 

I got things setup for the client and it works in singleplayer. I use git version control in my `.minecraft/` directory, and I cloned the repository into my server environment (I have lots of things ignored, I basically just sync datapacks and mods. I've been doing this for months, just separating server/client mods manually. The usage of git is not the issue. )

For the server, I get a crash during startup, this is the [console output](https://pastebin.com/DMu0q3fc).

`Could not create directory .\mods\.\mods\OPTIONAL` in the console prompted me to create the directory `mods/mods/`, and sure enough the game starts up if that exists, and any directories of selected rule options are created.

**Comment by EZForever** [comment]
Whoops, something must've got super wrong with `DirectoryModCandidateFinder`'s arguments. I didn't test ThatOrThis much in a server environment, guess I've misread something in Fabric's code.

**Comment by EZForever** [comment]
OK, fixed. That was a shameful mistake.

Please try [v0.1.1](https://github.com/EZForever/ThatOrThis/releases/tag/v0.1.1) and see if it works.

**Comment by supersaiyansubtlety** [comment]
It's working on the server now, thanks!
