### ISSUE TITLE
Add a modpack settings button.

### ISSUE THREAD

**Issue by Jefaxe** [EZForever/ThatOrThis#5]
I love this mod and it is making life so much easier, but i think it'd be even better if there was an icon like mod menu has, above that icon, or a bar (like mod menu) (configerable)

**Comment by EZForever** [comment]
Nice idea. How about having a icon-sized button laying right next to the ModMenu's button, just like the lock difficulty button? This way we can configure its position with ModMenu's settings.


![image](https://user-images.githubusercontent.com/34133756/110500054-c72f1980-8133-11eb-95d8-002163bcf80e.png)
*(Photoshopped image showing the estimated result)*

**Comment by JeffAxe123** [comment]
Yeah, thats just what i thought and i love it your details on it. I think 'Slight' GUI modifications allows right-click functionalities, but i don't think vanilla does.

**Comment by EZForever** [comment]
[v0.2.2](https://github.com/EZForever/ThatOrThis/releases/tag/v0.2.2) is released, with one or two more features that might also be helpful.

So is that right-clicking functionality working well as a "modpack settings button", or a dedicated button would be better?

**Comment by Jefaxe** [comment]
I was thinking a config option so the user can decide which is better.

**Comment by Jefaxe** [comment]
THIS RIGHT-CLICK IS AMAZING!
