### ISSUE TITLE
Dev option to crash on invalid rules.json

### ISSUE THREAD

**Issue by Jefaxe** [EZForever/ThatOrThis#7]
When creating my modpack, I am finding it annoying that when i make an error in rules.json, i have to close the game anyway to fix it.

It would be useful to have a (togglable,disabled by default) option to just crash when rules.json was invalid.

**Comment by EZForever** [comment]
Actually, if the game is launched without a valid `rules.json`, it will try to reload the configs each time you try to open the settings screen, until the configs are valid and loaded successfully. This behavior is not documented, but it is how the code works. For the configs to take effect though, you have to relaunch the game.

**Comment by EZForever** [comment]
Try this v0.2.2 snapshot: [thatorthis-0.2.2-indev+efbf978.jar.zip](https://github.com/EZForever/ThatOrThis/files/6113397/thatorthis-0.2.2-indev%2Befbf978.jar.zip) (unzip before installing).

It added the feature of opening modpack settings by right clicking the ModMenu button, bypassing ModMenu's screen cache. With this feature, you can right click ModMenu's button to request a config reload, until the config files are valid.

**Comment by Jefaxe** [comment]
Thanks! Reload is of course better than crash! Love the effort you are putting into this mod.
